defaultProject: cdf-data-extraction
defaultLocation: US
defaultDataset: neha_dataform
defaultAssertionDataset: dataform_assertions
dataformCoreVersion: 3.0.0-beta.4
vars:
  executionSetting: data